openapi: 3.0.0
info:
  description: 'Carbon Aware REST API'
  version: 0.1.0
  title: Carbon Aware REST API

paths:
  '/emissions/forecasts/current':
    get:
      summary: Get the current forecasted marginal carbon intensity for a given set of locations.
      description: Gets the most recent marginal carbon intensity forecast and returns the optimal start time for a window of a given duration.
      operationId: getCurrentMarginalCarbonIntensityForecast
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  '$ref': '#/components/schemas/EmissionsForecast'
              examples: 
                carbon-intensity-forecast-response:
                  '$ref': '#/components/examples/marginal-carbon-intensity-forecast-example'
        '501':
          description: Not Implemented
          content:
            application/json:
              schema:
                '$ref': '#/components/schemas/CarbonAwareError'
    parameters:
    - name: locations
      in: query
      description: 'Comma-separated list of names of the locations to be forecasted'
      required: true
      schema:
        type: string
      example: eastus
    - name: windowSize
      in: query
      description: 'The size/granularity (in minutes) of the time windows to report the forecasted average carbon intensity.'
      required: false
      schema:
        type: integer
      example: 60
    - name: notBefore
      in: query
      description: 'Scopes the forecast data to not before the provided date time.'
      required: false
      schema:
        type: string
        format: date-time
      example: '2022-05-23T00:00:00Z'
    - name: notAfter
      in: query
      description: 'Scopes the forecast data to not after the provided date time.'
      required: false
      schema:
        type: string
        format: date-time
      example: '2022-05-23T02:30:00Z'
  '/sci-scores':
    post:
      summary: Calculate the SCI score using the configured data sources
      description: ''
      operationId: calculateSciScore
      requestBody:
        '$ref': '#/components/requestBodies/MarginalCarbonIntensityCalculation'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                '$ref': '#/components/schemas/SciScore'
              examples: 
                sci-score-response:
                  '$ref': '#/components/examples/sci-score-response-example'
        '400':
          description: bad request
          content:
            application/json:
              schema:
                '$ref': '#/components/schemas/CarbonAwareError'
  '/sci-scores/marginal-carbon-intensity':
    post:
      summary: Calculate the average marginal carbon intensity for a given location and time duration.
      description: ''
      operationId: calculateMarginalCarbonIntensity
      requestBody:
        '$ref': '#/components/requestBodies/MarginalCarbonIntensityCalculation'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                '$ref': '#/components/schemas/SciScore'
              examples: 
                carbon-intensity-score-response:
                  '$ref': '#/components/examples/marginal-carbon-intensity-response-example'
        '400':
          description: bad request
          content:
            application/json:
              schema:
                '$ref': '#/components/schemas/CarbonAwareError'
components:
  requestBodies:
    SciScoreCalculation:
      content:
        application/json:
          schema:
            '$ref': '#/components/schemas/MarginalCarbonIntensityCalculation'
      description: Sci Score calculation component payload for configured data sources
      required: true
    MarginalCarbonIntensityCalculation:
      content:
        application/json:
          schema:
            '$ref': '#/components/schemas/MarginalCarbonIntensityCalculation'
      description: Marginal Carbon Intensity Calculation
      required: true
  schemas:
    EmissionsForecast:
      type: object
      properties:
        generatedAt:
          type: string
          format: date-time
        optimalDataPoint:
          '$ref': '#/components/schemas/EmissionsData'
        location:
          type: string
        notBefore:
          type: string
          format: date-time
        notAfter:
          type: string
          format: date-time
        forecastData:
          type: array
          items:
            '$ref': '#/components/schemas/EmissionsData'

    EmissionsData:
      type: object
      properties:
        location:
          type: string
        time:
          type: string
          format: date-time
        duration:
          type: integer
        rating:
          type: number
          format: float

    SciScore:
      type: object
      properties:
        sciScore:
          type: number
          format: float
        energyValue:
          type: number
          format: float
        marginalCarbonIntensityValue:
          type: number
          format: float
        embodiedEmissions:
          type: number
          format: float
        functionalUnit:
          type: integer
          format: int64

    MarginalCarbonIntensityCalculation:
      type: object
      properties:
        location:
          type: object
          description: JSON object that contains a locationType ("Geoposition" or "CloudProvider") and either latitude and longitude or the cloud provider and region
          properties:
            locationType:
              type: string
              enum:
                - Geoposition
                - CloudProvider
            latitude:
              type: number
              format: float
              example: 34.123
            longitude:
              type: number
              format: float
              example: 122.123
            providerName:
              type: string
              example: Azure
            regionName:
              type: string
              example: eastus
        timeInterval:
          type: string
          description: ISO8601 formatted [time interval](https://en.wikipedia.org/wiki/ISO_8601#Time_intervals).  This value should be supplied in the UTC (Z) timezone.
          example: 2007-03-01T13:00:00Z/2007-03-01T15:30:00Z

    CarbonAwareError:
      type: object
      properties:
        type:
          type: string
        title:
          type: string
        status:
          type: integer
        traceId:
          type: string
        errors:
          type: object
    
  examples:
    sci-score-response-example:
      summary: An example response from an SCI score calculation request
      value: {
        "sciScore": 750.0,
        "energyValue": 1.0,
        "marginalCarbonIntensityValue": 750.0,
        "embodiedEmissionsValue": 0.0,
        "functionalUnitValue": 1 
      }

    marginal-carbon-intensity-response-example:
      summary: An example response from Marginal Carbon Intensity calculation request.
      value: {
        "sciScore": null,
        "energyValue": null,
        "marginalCarbonIntensityValue": 750.0,
        "embodiedEmissionsValue": null,
        "functionalUnitValue": null 
      }
    
    marginal-carbon-intensity-forecast-example:
      summary: An example response from an emissions forecast request.
      value: [
        {
          "generatedAt": "2022-05-23T00:00:00Z",
          "optimalDataPoint": {
            "location": "eastus",
            "time": "2022-05-23T00:10:00Z",
            "rating": 173.3
          },
          "location": "eastus",
          "notBefore": "2022-05-23T00:00:00Z",
          "notAfter": "2022-05-23T00:21:00Z",
          "forecastData": [
            {
              "location": "eastus",
              "time": "2022-05-23T00:05:00Z",
              "rating": 195.2
            },
            {
              "location": "eastus",
              "time": "2022-05-23T00:10:00Z",
              "rating": 173.3
            },
            {
              "location": "eastus",
              "time": "2022-05-23T00:15:00Z",
              "rating": 222.4
            },
            {
              "location": "eastus",
              "time": "2022-05-23T00:20:00Z",
              "rating": 200.1
            },
          ]
        }
      ]