name: Build and Install GSF Packages on Sample ConsoleApp

on:
  push:
    branches: [ juzuluag/tooling_issue_workflow ]
    paths:
      - 'src/**'
      - '.github/workflows/**'
      - 'samples/lib-integration/ConsoleApp/**'
      - 'scripts/package/**'
    
  pull_request:
    types: [labeled]
    # branches: [ dev, main ]
    paths:
      - 'src/**'
      - '.github/workflows/**'
      - 'samples/lib-integration/ConsoleApp/**'
      - 'scripts/package/**'

env:
  DOTNET_SOLUTION: "src/CarbonAwareSDK.sln"
  OUTPUT_DIR: "packages"
  CONSOLE_APP: "samples/lib-integration/ConsoleApp/ConsoleApp.csproj"
  CONSOLE_DIR: "samples/lib-integration/ConsoleApp"
  CREATE_PKG: "scripts/package/create_packages.sh"
  ADD_PKG: "scripts/package/add_packages.sh"

jobs:
  dotnet-pack:
    # if: ${{ github.event.label.name == 'package' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup .NET Core SDK 6
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
          include-prerelease: false

      - name: Create packages
        run: ${{ env.CREATE_PKG }} ${{ env.DOTNET_SOLUTION }} ${{ env.OUTPUT_DIR }}

      - name: Restore current packages for ConsoleApp
        run: dotnet restore ${{ env.CONSOLE_APP }}

      - name: Add packages to ConsoleApp
        run: ${{ env.ADD_PKG }} ${{ env.CONSOLE_APP}} ${{ env.OUTPUT_DIR }}

      - name: Cat ConsoleApp project file
        run: cat ${{ env.CONSOLE_APP }}

      - name: Restore packages for ConsoleApp
        run: dotnet restore ${{ env.CONSOLE_APP }}

      - name: Build ConsoleApp
        run: dotnet build ${{ env.CONSOLE_APP }}
      
      - name: List content
        run: ls  -l samples/lib-integration/ConsoleApp/bin/Debug/net6.0/*.dll

      - name: Run ConsoleApp
        run: dotnet run 
        working-directory: ${{ env.CONSOLE_DIR }}
