name: Docker Web API Build

on:
  push:
    branches: [ dev, main, pritipathak/Auto_generate_Open_API ]
  pull_request:
    branches: [ dev, main ]
    paths:
      - 'src/dotnet/**'
      - '.github/workflows/**'

env:
  DOCKERFILE_PATH: "CarbonAware.WebApi/Dockerfile"
  HEALTH_ENDPOINT: "0.0.0.0:8080/health"
  DATA_ENDPOINT: "0.0.0.0:8080/emissions/bylocation?location=eastus"
  DOTNET_SRC_DIR: "./src/dotnet"
  DLL_FILE_PATH: "./src/dotnet/CarbonAware.WebApi/bin/Release/net6.0/CarbonAware.WebApi.dll"

jobs:
  container-dotnet-build:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK 6
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
          include-prerelease: false
      - name: Install dependencies
        run: dotnet restore
        working-directory: ${{ env.DOTNET_SRC_DIR }}
      - name: Install tools
        run: dotnet tool restore #--tool-manifest  .config/dotnet-tools.json
        working-directory: ${{ env.DOTNET_SRC_DIR }}
      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: ${{ env.DOTNET_SRC_DIR }}
      # - name: Test + Code Coverage
      #   run: dotnet test --no-restore --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
      #   working-directory: ${{ env.DOTNET_SRC_DIR }}
      # - name: Codecov
      #   uses: codecov/codecov-action@v1
      # - name: Open API generation
      #   run: dotnet swagger tofile --output ./api/v1/swagger.yaml --yaml ${{ env.DLL_FILE_PATH }} v1 WorkingDirectory = ${{ env.DOTNET_SRC_DIR }}   
      
      - name: Open API generation
        run: swagger

  container-validation:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Docker Target Final
        run: docker build . -f ${DOCKERFILE_PATH} -t ca-api
        working-directory: ./src/dotnet
        
      - name: Docker Run Container
        run: |
          docker run -d --name runnable-container -p 8080:80 ca-api
          docker container ls

      - name: Docker WGET Health Endpoint
        run: |
          wget -t 5 --waitretry=5 ${HEALTH_ENDPOINT}

      - name: Docker WGET Data Endpoint
        run: |
          wget -t 5 --waitretry=5 ${DATA_ENDPOINT}

